# frozen_string_literal: true

@opensource_hash = { 'OS1' => '"Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something." ~ Richard Stallman',
                     'OS2' => '"Programming is not a science. Programming is a craft." ~ Richard Stallman',
                     'OS3' => '"I did write some code in Java once, but that was the island in Indonesia." ~ Richard Stallman',
                     'OS4' => '"Free software is software that respects your freedom and the social solidarity of your community. So its free as in freedom." ~ Richard Stallman',
                     'OS5' => '"Sharing is good, and with digital technology, sharing is easy." ~ Richard Stallman',
                     'OS7' => '"I suppose many people will continue moving towards careless computing, because there is a sucker born every minute." ~ Richard Stallman',
                     'OS8' => '"There is no system but GNU and Linux is one of it is kernels" ~ Richard Stallman',
                     'OS9' => '"Proprietary software tends to have malicious features. The point is with a proprietary program, when the users dont have the source code, we can never tell. So you must consider every proprietary program as potential malware." ~ Richard Stallman',
                     'OS10' => '"Idiots can be defeated but they never admit it." ~ Richard Stallman',
                     'OS11' => '"No person, no idea, and no religion deserves to be illegal to insult, not even the Church of Emacs." ~ Richard Stallman',
                     'OS12' => '"Playfully doing something difficult, whether useful or not, that is hacking." ~ Richard Stallman',
                     'OS13' => '"Things like freedom and the expansion of knowledge are beyond success, beyond the personal. Personal success is not wrong, but it is limited in importance." ~ Richard Stallman',
                     'OS14' => '"I could have made money this way, and perhaps amused myself writing code. But I knew that at the end of my career, I would look back on years of building walls to divide people, and feel I had spent my life making the world a worse place."  ~ Richard Stallman',
                     'OS15' => '"Laws that oppress people have no moral authority" ~ Richard Stallman',
                     'OS16' => '"It is unfortunate that he still has nonfree software in his computer. He needs to defenestrate it (which means, either throw Windows out of the computer or throw the computer out of the window)."  ~ Richard Stallman',
                     'OS17' => '"If the users do not control the program, the program controls the users ... A nonfree program is a yoke, an instrument of unjust power."  ~ Richard Stallman' }

@motivate_hash = { 'M1' => '“All our dreams can come true, if we have the courage to pursue them.” – Walt Disney',
                   'M2' => '“The secret of getting ahead is getting started.” – Mark Twain',
                   'M3' => '“I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life and that is why I succeed.” – Michael Jordan',
                   'M4' => '“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” – Mary Kay Ash',
                   'M5' => '“It’s hard to beat a person who never gives up.” – Babe Ruth',
                   'M7' => '“I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’” – Leah Busque',
                   'M8' => '“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz',
                   'M9' => '“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” – Arianna Huffington',
                   'M10' => '“Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE.” – Joss Whedon',
                   'M11' => '“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”― Neil Gaiman',
                   'M12' => '“Everything you can imagine is real.”― Pablo Picasso',
                   'M13' => '“When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.” ― Helen Keller',
                   'M14' => '“Do one thing every day that scares you.”― Eleanor Roosevelt',
                   'M15' => '“It’s no use going back to yesterday, because I was a different person then.”― Lewis Carroll',
                   'M16' => '“Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.” – Socrates',
                   'M17' => '“Happiness is not something ready made. It comes from your own actions.” ― Dalai Lama XIV',
                   'M18' => '“Whatever you are, be a good one.” ― Abraham Lincoln',
                   'M19' => '“Impossible is just an opinion.” – Paulo Coelho',
                   'M20' => '“You can either experience the pain of discipline or the pain of regret. The choice is yours.”  – Unknown',
                   'M21' => '“If we have the attitude that it’s going to be a great day it usually is.” – Catherine Pulsifier',
                   'M23' => '“If something is important enough, even if the odds are stacked against you, you should still do it.” – Elon Musk',
                   'M24' => '“Hold the vision, trust the process.” – Unknown',
                   'M25' => '“Don’t be afraid to give up the good to go for the great.” – John D. Rockefeller',
                   'M26' => '“People who wonder if the glass is half empty or full miss the point. The glass is refillable.” – Unknown',
                   'M27' => '“Every sucessful person in the world is a hustler one way or another. We all hustle to get where we need to be. Only a fool would sit around and wait on another man to feed him.” ― K’wan' }

@inspire_hash = { 'IN1' => '“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler',
                  'IN3' => '“First, solve the problem. Then, write the code.” – John Johnson',
                  'IN4' => '“Experience is the name everyone gives to their mistakes.” – Oscar Wilde',
                  'IN5' => '“ In order to be irreplaceable, one must always be different” – Coco Chanel',
                  'IN7' => '“Java is to JavaScript what car is to Carpet.” – Chris Heilmann',
                  'IN8' => '“Knowledge is power.” – Francis Bacon',
                  'IN9' => '“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.” – Dan Salomon',
                  'IN10' => '“Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.” – Antoine de Saint-Exupery',
                  'IN11' => '“ Code is like humor. When you have to explain it, it’s bad.” – Cory House',
                  'IN12' => '“Fix the cause, not the symptom.” – Steve Maguire',
                  'IN13' => '“Optimism is an occupational hazard of programming: feedback is the treatment. “ Kent Beck',
                  'IN14' => '“When to use iterative development? You should use iterative development only on projects that you want to succeed.” – Martin Fowler',
                  'IN15' => '“Simplicity is the soul of efficiency.” – Austin Freeman',
                  'IN16' => '“Before software can be reusable it first has to be usable.” – Ralph Johnson',
                  'IN17' => 'Most good programmers do programming not because they expect to get paid or get adulation by the public, but it is fun to program.',
                  'IN18' => 'When someone says, “I want a programming language in which I need only say what I want done,” give him a lollipop.',
                  'IN19' => 'Programming is like sex. One mistake and you have to support it for the rest of your life.',
                  'IN20' => 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.',
                  'IN21' => ' Good design adds value faster than it adds cost.',
                  'IN22' => 'Programs must be written for people to read, and only incidentally for machines to execute.',
                  'IN23' => '“Make it work, make it right, make it fast.” – Kent Beck' }

@ilustrate_hash = { 'I1' => '"Research shows that one of the biggest and most burdensome challenges for software project leaders is the team’s capacity in relation to the number of tasks in the backlog." ~ thecodest.co',
                    'I2' => '"Over 50% of companies that use software development to develop their own products declare that they have used or benefited from outsourcing their programming. They choose this option due to both high-quality guarantees and cost-effectiveness." ~ thecodest.co',
                    'I3' => '"According to the Stack OverFlow study, JavaScript is the most popular programming language in 2020. The next places are occupied by HTML / CSS and SQL. Technologies such as Ruby, Java and Python have maintained a stable position over the years." ~ thecodest.co',
                    'I4' => '"Scrum is the most often Agile Software Development methodology in 2020. You can see a clear advantage of this approach to project development if compared to other methodologies." ~ thecodest.co',
                    'I5' => '"Jira is the most-used tool for managing software development projects. This is pointed out by almost half of the surveyed people. Trello is second most popular. In the case of communication tools, Slack (58.66%) wins, followed by e-mail (45.06%), and then Jira (26.32%)." ~ thecodest.co',
                    'I6' => '"76% of the companies surveyed in the Coding Sans report admit that they allow their employees to work remotely. These statistics reflect the prevailing world trend." ~ thecodest.co',
                    'I7' => '"GitHub was indicated by 43% of people as the control system they use. Bitbucket was chosen by 20%, while 16.70% indicated GitLab" ~ thecodest.co',
                    'I8' => '"60% of the respondents declare that they prefer in-person meetings when it comes to communication regarding project milestones, releases or deadlines." ~ thecodest.co',
                    'I9' => '"On average, there are five job positions per one developer. This trend shows a huge demand for programmers." ~ thecodest.co',
                    'I10' => '"Nearly 15% of surveyed companies declare that unrealistic expectations regarding projects in development cause the most frequent delays in work." ~ thecodest.co',
                    'I11' => '"About 14.52% of surveyed companies pointed that improper estimations cause the most frequent delays in work, 12.21% of companies admit that, incorrect specification of goals caused the main problems." ~ thecodest.co',
                    'I12' => '"The first Computer Programmer was an English woman called Ada Lovelace who was born in 1815" ~ Mercury Solutions',
                    'I13' => '"If computer programming was a country it would have held the 2nd most diversity in the numer of lenguages with more than 700 approx" ~ Mercury Solutions',
                    'I14' => '"Commonly, a full-stack developer usually knows 4-6 main programming languages and frameworks" ~ Mercury Solutions',
                    'I15' => '"1 in every 3 developer wrote the first code before even finish school" ~ Mercury Solutions',
                    'I16' => '"men make up the majority of developers, range at 85-89% of the usual workforce" ~ Mercury Solutions',
                    'I17' => '"Perl is one of the most popular language, and known as SWISS ARMY KNIFE of programming languages" \~ Mercury Solutions',
                    'I18' => '"Among all the latest one, most software developers love working on Wndows as theri main OS" ~ Mercury Solutions',
                    'I19' => '"There is an entire industry Coding Bootcamps of $240 M value and will graduate ~22.000 developers till 2020" ~ Mercury Solutions' }

@opensource_history = {}
@motivate_history = {}
@inspire_history = {}
@ilustrate_history = {}
